services:
  postgres:
    container_name: mc_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${MC_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${MC_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${MC_DB_NAME:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./database/migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - ${MC_DB_PORT:-5432}:5432
    restart: unless-stopped

volumes:
    postgres: {}