"""create pricestamps table

Revision ID: 9c5a3e031784
Revises: 
Create Date: 2023-06-12 20:41:13.978544

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9c5a3e031784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pricestamps',
        sa.Column('pricestamp_idx', sa.UUID(), nullable=False, server_default=sa.sql.expression.func.gen_random_uuid()),
        sa.Column('ticker', sa.String(length=8), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('pricestamp_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricestamps')
    # ### end Alembic commands ###
